### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by Abramovick** [winstrike/next-i18next-koa#1]
## Describe the solution you'd like
I’d like to install via yarn or npm and do something like `yarn add next-i18next-koa`

## Additional context
Some people in my team aren’t sure how to set this up, others have run `yarn && yarn build` and then just copied the `dist` folder manually and added it to the project. It seems like the `dist` folder doesn’t exist by default and you have to manually build it… Can you add a kind of “best practice” installation process to the readme file?

**Comment by Janealter** [comment]
The command for install this package is `yarn add @winstrike/next-i18next-koa`. The `dist` folder doesn't exist by default because it should not be part of the source code.

I added the install commands in the readme in commit 6c13cfcda65f7aa4e8ffc5f5c8fb082fc72dfbf2.
